### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by ghost** [TheCodingBeast/TCB_HUD_V2#1]
HELP

[ERROR] addons/darkrpmodification/lua/darkrp_modules/tcb_hud_2/cl_main.lua:366: attempt to concatenate a nil value
1. DrawPlayerInfo - addons/darkrpmodification/lua/darkrp_modules/tcb_hud_2/cl_main.lua:366
   1. DrawEntityDisplay - addons/darkrpmodification/lua/darkrp_modules/tcb_hud_2/cl_main.lua:424
   2. fn - addons/darkrpmodification/lua/darkrp_modules/tcb_hud_2/cl_main.lua:475
      1. unknown - addons/ulib/lua/ulib/shared/hook.lua:110

**Comment by AnthonyFuller** [comment]
It has been fixed; Fix #1
